export const  AUTH_TOKEN = "AUTH_TOKEN";
export const  DELETE_TOKEN = "DELETE_TOKEN";
export const  BASECAKES_LIST = "BASECAKES_LIST";
export const  BASECAKES_EDIT_LIST = "BASECAKES_EDIT_LIST";
export const  INGREDIENTS_LIST = "INGREDIENTS_LIST";
export const  ORDERS_LIST = "ORDERS_LIST";